"""removed pet type in table pet

Revision ID: 72cc4edf63a5
Revises: 72cdf049f950
Create Date: 2024-07-09 15:43:04.691963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72cc4edf63a5'
down_revision = '72cdf049f950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
