"""initial migration

Revision ID: 315265a07cc3
Revises: 
Create Date: 2024-07-03 17:14:29.941329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315265a07cc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
